# Generated by Django 5.1.4 on 2024-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('nif', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('endereco', models.CharField(max_length=50)),
                ('numero_de_conta', models.IntegerField()),
                ('numero_do_contador', models.IntegerField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
