# Generated by Django 5.1.4 on 2024-12-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carregarrecarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='1234', max_length=50),
            preserve_default=False,
        ),
    ]
