# Generated by Django 5.1.4 on 2024-12-07 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_debito_directo', models.BooleanField()),
                ('iban', models.CharField(max_length=40)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('id_do_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
