# Generated by Django 5.1.4 on 2024-12-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_informacoescliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacoescliente',
            name='limite_de_carregamento_mensal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
